# image
# 参考: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_start_a_single_node_cluster
FROM docker.elastic.co/elasticsearch/elasticsearch:8.12.0
# プラグイン インストール:日本語解析
RUN elasticsearch-plugin install analysis-kuromoji